export default {
    audio: [
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //20
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //30
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //40
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //50
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //60
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //70
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //80
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //90
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //100
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //110
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //120
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //130
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        //140
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/EmissionAmbianceSalon.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3')),
        new Audio(require('@/audio/DéfileAmbiance.mp3')),
        new Audio(require('@/audio/RomanPhotoAmbianceSalon.mp3'))
    ],
    photo: [
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //10
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //20
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //30
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //40
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //50
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //60
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //70
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //80
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //90
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //100
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //110
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //120
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //130
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        //140
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif"),
        require("@/assets/Zapping.jpg"),
        require("@/assets/loge4.jpg"),
        require("@/assets/gif_channel1.gif"),
        require("@/assets/gif_channel2.gif"),
        require("@/assets/gif_channel3.gif")
    ]
}